#.travis.yml

language: node_js
node_js:
  - "8.10"

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    repo: devadvance/sms-backup-reader-2
    tags: true
